services:
  - type: web
    name: sat-frame-interpolator
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
